const domande = [
    "Dov'è Sergio?",
    "Ma Sergio?",
    "C'è Sergio?",
    "Dov'è andato Sergio?"
];

const risposte = [
    "E tu sei?",
    "Ma che ce futt",
    "A pranzo.",
    "L'abbiamo visto entrare in una cabina telefonica, ma poi è uscito Superman.",
    "Ha preso un taxi urlando ‹Segua quella macchina!›",
    "Ha risposto al transponder e Scotty l'ha portato su.",
    "Si è imbarcato in una missione quinquennale alla ricerca di nuovi mondi.",
    "Potrei dirtelo, ma poi dovrei ucciderti.",
    "E' appena arrivata la lettera da Hogwarts.",
    "Ha avuto una rivelazione sulla via di Damasco.",
    "E la cremeria?",
    "A caccia di wezen",
    "Al Lux a suonare il piano con Lucifer",
    "A dar da mangiare al fucsbau",
    "In una galassia lontana lontana",
    "Imprigionato da una Hexembist",
    "Sulla Salerno-Reggio Calabria...",
    "No dai",
    "Sergino tremendino",
    "composer install sergio",
    "npm install sergio",
    "È a Napoli",
    "È qui solo che non lo vedi",
    "Eh, la crisi.",
    "Fin dove si lavano la faccia i pelati?",
    "Alla fine dell'arcobaleno.",
    "Il vero Sergio è sempre stato nei nostri cuori.",
    "Nella terra dei cachi.",
    "Guarda dentro di te e troverai la risposta.",
    "Usa la forza, Luke.",
    "Parola d'ordine?",
    "Convocato in nazionale.",
    "Alla fermata del destino.",
    "E tu dove sei?",
    "Sulla Luna boscosa di Endor.",
    "Sei il nostro milionesimo visitatore!",
    "Nella mano destra o nella mano sinistra?",
    "Nella foresta nera a cercare il tesoro dei Grimm.",
    "In missione per il Vallo.",
    "Fumata bianca, l'hanno chiamato al Vaticano proprio ora.",
    "Nick Fury ha chiamato, gli serve un developer.",
    "A cercare le sfere del drago.",
    "User not in sudoers file, incident will be reported.",
    "500 server error",
    "Eletto con due terzi dei voti al parlamento in seduta plenaria: ora lo devi chiamare Signor Presidente.",
    "Eh, brutta l'abolizione della schiavitu' eh?"
]; 

export { domande, risposte };
